export type StockEntry = {
  symbol: string;
  name: string;
  exchange: "NASDAQ" | "NYSE" | "AMEX";
  sector: string;
};

export const STOCKS_DB: StockEntry[] = [
  // Technology
  { symbol: "AAPL",  name: "Apple Inc.",               exchange: "NASDAQ", sector: "Technology" },
  { symbol: "MSFT",  name: "Microsoft Corp.",           exchange: "NASDAQ", sector: "Technology" },
  { symbol: "GOOGL", name: "Alphabet Inc.",             exchange: "NASDAQ", sector: "Technology" },
  { symbol: "GOOG",  name: "Alphabet Inc. Class C",     exchange: "NASDAQ", sector: "Technology" },
  { symbol: "META",  name: "Meta Platforms",            exchange: "NASDAQ", sector: "Technology" },
  { symbol: "NVDA",  name: "NVIDIA Corp.",              exchange: "NASDAQ", sector: "Semiconductors" },
  { symbol: "AMD",   name: "Advanced Micro Devices",    exchange: "NASDAQ", sector: "Semiconductors" },
  { symbol: "INTC",  name: "Intel Corp.",               exchange: "NASDAQ", sector: "Semiconductors" },
  { symbol: "QCOM",  name: "Qualcomm Inc.",             exchange: "NASDAQ", sector: "Semiconductors" },
  { symbol: "AVGO",  name: "Broadcom Inc.",             exchange: "NASDAQ", sector: "Semiconductors" },
  { symbol: "TSM",   name: "Taiwan Semiconductor",      exchange: "NYSE",   sector: "Semiconductors" },
  { symbol: "ASML",  name: "ASML Holding",              exchange: "NASDAQ", sector: "Semiconductors" },
  { symbol: "MU",    name: "Micron Technology",         exchange: "NASDAQ", sector: "Semiconductors" },
  { symbol: "AMAT",  name: "Applied Materials",         exchange: "NASDAQ", sector: "Semiconductors" },
  { symbol: "LRCX",  name: "Lam Research",              exchange: "NASDAQ", sector: "Semiconductors" },
  { symbol: "KLAC",  name: "KLA Corp.",                 exchange: "NASDAQ", sector: "Semiconductors" },
  { symbol: "ADBE",  name: "Adobe Inc.",                exchange: "NASDAQ", sector: "Software" },
  { symbol: "CRM",   name: "Salesforce Inc.",           exchange: "NYSE",   sector: "Software" },
  { symbol: "ORCL",  name: "Oracle Corp.",              exchange: "NYSE",   sector: "Software" },
  { symbol: "NOW",   name: "ServiceNow",                exchange: "NYSE",   sector: "Software" },
  { symbol: "SNOW",  name: "Snowflake Inc.",            exchange: "NYSE",   sector: "Software" },
  { symbol: "PLTR",  name: "Palantir Technologies",     exchange: "NASDAQ", sector: "Software" },
  { symbol: "PANW",  name: "Palo Alto Networks",        exchange: "NASDAQ", sector: "Cybersecurity" },
  { symbol: "CRWD",  name: "CrowdStrike Holdings",      exchange: "NASDAQ", sector: "Cybersecurity" },
  { symbol: "FTNT",  name: "Fortinet Inc.",             exchange: "NASDAQ", sector: "Cybersecurity" },
  { symbol: "ZS",    name: "Zscaler Inc.",              exchange: "NASDAQ", sector: "Cybersecurity" },
  { symbol: "NET",   name: "Cloudflare Inc.",           exchange: "NYSE",   sector: "Technology" },
  { symbol: "DDOG",  name: "Datadog Inc.",              exchange: "NASDAQ", sector: "Software" },
  { symbol: "TEAM",  name: "Atlassian Corp.",           exchange: "NASDAQ", sector: "Software" },
  { symbol: "SHOP",  name: "Shopify Inc.",              exchange: "NYSE",   sector: "Technology" },
  { symbol: "TWLO",  name: "Twilio Inc.",               exchange: "NYSE",   sector: "Software" },
  { symbol: "OKTA",  name: "Okta Inc.",                 exchange: "NASDAQ", sector: "Software" },
  { symbol: "PATH",  name: "UiPath Inc.",               exchange: "NYSE",   sector: "Software" },
  { symbol: "AI",    name: "C3.ai Inc.",                exchange: "NYSE",   sector: "AI" },
  { symbol: "SOUN",  name: "SoundHound AI",             exchange: "NASDAQ", sector: "AI" },
  { symbol: "BBAI",  name: "BigBear.ai",                exchange: "NYSE",   sector: "AI" },
  // E-commerce & Consumer Internet
  { symbol: "AMZN",  name: "Amazon.com Inc.",           exchange: "NASDAQ", sector: "E-commerce" },
  { symbol: "BABA",  name: "Alibaba Group",             exchange: "NYSE",   sector: "E-commerce" },
  { symbol: "JD",    name: "JD.com Inc.",               exchange: "NASDAQ", sector: "E-commerce" },
  { symbol: "EBAY",  name: "eBay Inc.",                 exchange: "NASDAQ", sector: "E-commerce" },
  { symbol: "ETSY",  name: "Etsy Inc.",                 exchange: "NASDAQ", sector: "E-commerce" },
  { symbol: "UBER",  name: "Uber Technologies",         exchange: "NYSE",   sector: "Technology" },
  { symbol: "LYFT",  name: "Lyft Inc.",                 exchange: "NASDAQ", sector: "Technology" },
  { symbol: "DASH",  name: "DoorDash Inc.",             exchange: "NASDAQ", sector: "Technology" },
  { symbol: "ABNB",  name: "Airbnb Inc.",               exchange: "NASDAQ", sector: "Travel Tech" },
  { symbol: "BKNG",  name: "Booking Holdings",          exchange: "NASDAQ", sector: "Travel Tech" },
  { symbol: "EXPE",  name: "Expedia Group",             exchange: "NASDAQ", sector: "Travel Tech" },
  // Social / Media
  { symbol: "NFLX",  name: "Netflix Inc.",              exchange: "NASDAQ", sector: "Streaming" },
  { symbol: "DIS",   name: "Walt Disney Co.",           exchange: "NYSE",   sector: "Media" },
  { symbol: "PARA",  name: "Paramount Global",          exchange: "NASDAQ", sector: "Media" },
  { symbol: "ROKU",  name: "Roku Inc.",                 exchange: "NASDAQ", sector: "Streaming" },
  { symbol: "SPOT",  name: "Spotify Technology",        exchange: "NYSE",   sector: "Streaming" },
  { symbol: "SNAP",  name: "Snap Inc.",                 exchange: "NYSE",   sector: "Social Media" },
  { symbol: "PINS",  name: "Pinterest Inc.",            exchange: "NYSE",   sector: "Social Media" },
  { symbol: "RDDT",  name: "Reddit Inc.",               exchange: "NYSE",   sector: "Social Media" },
  // Fintech & Payments
  { symbol: "V",     name: "Visa Inc.",                 exchange: "NYSE",   sector: "Payments" },
  { symbol: "MA",    name: "Mastercard Inc.",           exchange: "NYSE",   sector: "Payments" },
  { symbol: "PYPL",  name: "PayPal Holdings",           exchange: "NASDAQ", sector: "Fintech" },
  { symbol: "SQ",    name: "Block Inc.",                exchange: "NYSE",   sector: "Fintech" },
  { symbol: "AFRM",  name: "Affirm Holdings",           exchange: "NASDAQ", sector: "Fintech" },
  { symbol: "SOFI",  name: "SoFi Technologies",         exchange: "NASDAQ", sector: "Fintech" },
  { symbol: "COIN",  name: "Coinbase Global",           exchange: "NASDAQ", sector: "Crypto" },
  { symbol: "MSTR",  name: "MicroStrategy",             exchange: "NASDAQ", sector: "Crypto" },
  { symbol: "HOOD",  name: "Robinhood Markets",         exchange: "NASDAQ", sector: "Fintech" },
  // Healthcare & Biotech
  { symbol: "JNJ",   name: "Johnson & Johnson",         exchange: "NYSE",   sector: "Healthcare" },
  { symbol: "PFE",   name: "Pfizer Inc.",               exchange: "NYSE",   sector: "Pharma" },
  { symbol: "MRK",   name: "Merck & Co.",               exchange: "NYSE",   sector: "Pharma" },
  { symbol: "ABBV",  name: "AbbVie Inc.",               exchange: "NYSE",   sector: "Pharma" },
  { symbol: "LLY",   name: "Eli Lilly and Co.",         exchange: "NYSE",   sector: "Pharma" },
  { symbol: "BMY",   name: "Bristol-Myers Squibb",      exchange: "NYSE",   sector: "Pharma" },
  { symbol: "AMGN",  name: "Amgen Inc.",                exchange: "NASDAQ", sector: "Biotech" },
  { symbol: "GILD",  name: "Gilead Sciences",           exchange: "NASDAQ", sector: "Biotech" },
  { symbol: "BIIB",  name: "Biogen Inc.",               exchange: "NASDAQ", sector: "Biotech" },
  { symbol: "MRNA",  name: "Moderna Inc.",              exchange: "NASDAQ", sector: "Biotech" },
  { symbol: "REGN",  name: "Regeneron Pharma",          exchange: "NASDAQ", sector: "Biotech" },
  { symbol: "VRTX",  name: "Vertex Pharmaceuticals",    exchange: "NASDAQ", sector: "Biotech" },
  { symbol: "ISRG",  name: "Intuitive Surgical",        exchange: "NASDAQ", sector: "MedTech" },
  { symbol: "MDT",   name: "Medtronic PLC",             exchange: "NYSE",   sector: "MedTech" },
  { symbol: "SYK",   name: "Stryker Corp.",             exchange: "NYSE",   sector: "MedTech" },
  { symbol: "BSX",   name: "Boston Scientific",         exchange: "NYSE",   sector: "MedTech" },
  { symbol: "UNH",   name: "UnitedHealth Group",        exchange: "NYSE",   sector: "Insurance" },
  { symbol: "CVS",   name: "CVS Health Corp.",          exchange: "NYSE",   sector: "Healthcare" },
  // Defense & Aerospace
  { symbol: "LMT",   name: "Lockheed Martin",           exchange: "NYSE",   sector: "Defense" },
  { symbol: "RTX",   name: "RTX Corp.",                 exchange: "NYSE",   sector: "Defense" },
  { symbol: "NOC",   name: "Northrop Grumman",          exchange: "NYSE",   sector: "Defense" },
  { symbol: "GD",    name: "General Dynamics",          exchange: "NYSE",   sector: "Defense" },
  { symbol: "BA",    name: "Boeing Co.",                exchange: "NYSE",   sector: "Aerospace" },
  { symbol: "HII",   name: "Huntington Ingalls",        exchange: "NYSE",   sector: "Defense" },
  { symbol: "LHX",   name: "L3Harris Technologies",     exchange: "NYSE",   sector: "Defense" },
  { symbol: "LDOS",  name: "Leidos Holdings",           exchange: "NYSE",   sector: "Defense" },
  // Energy
  { symbol: "XOM",   name: "Exxon Mobil Corp.",         exchange: "NYSE",   sector: "Energy" },
  { symbol: "CVX",   name: "Chevron Corp.",             exchange: "NYSE",   sector: "Energy" },
  { symbol: "COP",   name: "ConocoPhillips",            exchange: "NYSE",   sector: "Energy" },
  { symbol: "SLB",   name: "SLB (Schlumberger)",        exchange: "NYSE",   sector: "Energy Services" },
  { symbol: "EOG",   name: "EOG Resources",             exchange: "NYSE",   sector: "Energy" },
  { symbol: "OXY",   name: "Occidental Petroleum",      exchange: "NYSE",   sector: "Energy" },
  { symbol: "PSX",   name: "Phillips 66",               exchange: "NYSE",   sector: "Energy" },
  { symbol: "VLO",   name: "Valero Energy",             exchange: "NYSE",   sector: "Energy" },
  // Electric Vehicles & Clean Energy
  { symbol: "TSLA",  name: "Tesla Inc.",                exchange: "NASDAQ", sector: "Electric Vehicles" },
  { symbol: "RIVN",  name: "Rivian Automotive",         exchange: "NASDAQ", sector: "Electric Vehicles" },
  { symbol: "LCID",  name: "Lucid Group",               exchange: "NASDAQ", sector: "Electric Vehicles" },
  { symbol: "NIO",   name: "NIO Inc.",                  exchange: "NYSE",   sector: "Electric Vehicles" },
  { symbol: "XPEV",  name: "XPeng Inc.",                exchange: "NYSE",   sector: "Electric Vehicles" },
  { symbol: "ENPH",  name: "Enphase Energy",            exchange: "NASDAQ", sector: "Clean Energy" },
  { symbol: "FSLR",  name: "First Solar Inc.",          exchange: "NASDAQ", sector: "Clean Energy" },
  { symbol: "NEE",   name: "NextEra Energy",            exchange: "NYSE",   sector: "Clean Energy" },
  // Financials & Banks
  { symbol: "JPM",   name: "JPMorgan Chase & Co.",      exchange: "NYSE",   sector: "Banking" },
  { symbol: "BAC",   name: "Bank of America",           exchange: "NYSE",   sector: "Banking" },
  { symbol: "WFC",   name: "Wells Fargo & Co.",         exchange: "NYSE",   sector: "Banking" },
  { symbol: "C",     name: "Citigroup Inc.",            exchange: "NYSE",   sector: "Banking" },
  { symbol: "GS",    name: "Goldman Sachs",             exchange: "NYSE",   sector: "Investment Banking" },
  { symbol: "MS",    name: "Morgan Stanley",            exchange: "NYSE",   sector: "Investment Banking" },
  { symbol: "BLK",   name: "BlackRock Inc.",            exchange: "NYSE",   sector: "Asset Management" },
  { symbol: "SCHW",  name: "Charles Schwab",            exchange: "NYSE",   sector: "Brokerage" },
  { symbol: "AXP",   name: "American Express",          exchange: "NYSE",   sector: "Payments" },
  { symbol: "BRK.B", name: "Berkshire Hathaway B",      exchange: "NYSE",   sector: "Conglomerate" },
  { symbol: "CB",    name: "Chubb Ltd.",                exchange: "NYSE",   sector: "Insurance" },
  { symbol: "MET",   name: "MetLife Inc.",              exchange: "NYSE",   sector: "Insurance" },
  // Consumer Staples
  { symbol: "PG",    name: "Procter & Gamble",          exchange: "NYSE",   sector: "Consumer Staples" },
  { symbol: "KO",    name: "Coca-Cola Co.",             exchange: "NYSE",   sector: "Beverages" },
  { symbol: "PEP",   name: "PepsiCo Inc.",              exchange: "NASDAQ", sector: "Beverages" },
  { symbol: "MCD",   name: "McDonald's Corp.",          exchange: "NYSE",   sector: "Restaurants" },
  { symbol: "SBUX",  name: "Starbucks Corp.",           exchange: "NASDAQ", sector: "Restaurants" },
  { symbol: "WMT",   name: "Walmart Inc.",              exchange: "NYSE",   sector: "Retail" },
  { symbol: "TGT",   name: "Target Corp.",              exchange: "NYSE",   sector: "Retail" },
  { symbol: "COST",  name: "Costco Wholesale",          exchange: "NASDAQ", sector: "Retail" },
  { symbol: "HD",    name: "Home Depot Inc.",           exchange: "NYSE",   sector: "Retail" },
  { symbol: "LOW",   name: "Lowe's Companies",          exchange: "NYSE",   sector: "Retail" },
  { symbol: "NKE",   name: "Nike Inc.",                 exchange: "NYSE",   sector: "Consumer" },
  { symbol: "LULU",  name: "Lululemon Athletica",       exchange: "NASDAQ", sector: "Consumer" },
  { symbol: "AMZN",  name: "Amazon.com Inc.",           exchange: "NASDAQ", sector: "E-commerce" },
  // Industrials
  { symbol: "CAT",   name: "Caterpillar Inc.",          exchange: "NYSE",   sector: "Industrials" },
  { symbol: "DE",    name: "Deere & Company",           exchange: "NYSE",   sector: "Industrials" },
  { symbol: "MMM",   name: "3M Company",                exchange: "NYSE",   sector: "Industrials" },
  { symbol: "HON",   name: "Honeywell International",   exchange: "NASDAQ", sector: "Industrials" },
  { symbol: "GE",    name: "GE Aerospace",              exchange: "NYSE",   sector: "Industrials" },
  { symbol: "UPS",   name: "United Parcel Service",     exchange: "NYSE",   sector: "Logistics" },
  { symbol: "FDX",   name: "FedEx Corp.",               exchange: "NYSE",   sector: "Logistics" },
  { symbol: "ZIM",   name: "ZIM Integrated Shipping",   exchange: "NYSE",   sector: "Shipping" },
  { symbol: "DAL",   name: "Delta Air Lines",           exchange: "NYSE",   sector: "Airlines" },
  { symbol: "UAL",   name: "United Airlines",           exchange: "NASDAQ", sector: "Airlines" },
  { symbol: "AAL",   name: "American Airlines",         exchange: "NASDAQ", sector: "Airlines" },
  { symbol: "LUV",   name: "Southwest Airlines",        exchange: "NYSE",   sector: "Airlines" },
  // Real Estate
  { symbol: "AMT",   name: "American Tower Corp.",      exchange: "NYSE",   sector: "REIT" },
  { symbol: "PLD",   name: "Prologis Inc.",             exchange: "NYSE",   sector: "REIT" },
  { symbol: "EQIX",  name: "Equinix Inc.",              exchange: "NASDAQ", sector: "Data Center REIT" },
  { symbol: "CCI",   name: "Crown Castle Inc.",         exchange: "NYSE",   sector: "REIT" },
  // ETFs
  { symbol: "SPY",   name: "SPDR S&P 500 ETF",         exchange: "NYSE",   sector: "ETF" },
  { symbol: "QQQ",   name: "Invesco QQQ Trust",         exchange: "NASDAQ", sector: "ETF" },
  { symbol: "IWM",   name: "iShares Russell 2000",      exchange: "NYSE",   sector: "ETF" },
  { symbol: "GLD",   name: "SPDR Gold Shares",          exchange: "NYSE",   sector: "ETF" },
  { symbol: "TLT",   name: "iShares 20Y Treasury",      exchange: "NASDAQ", sector: "ETF" },
  { symbol: "VXX",   name: "iPath Series B VIX",        exchange: "NYSE",   sector: "ETF" },
  { symbol: "ITA",   name: "iShares Defense ETF",       exchange: "NYSE",   sector: "ETF" },
  { symbol: "XLE",   name: "Energy Select SPDR",        exchange: "NYSE",   sector: "ETF" },
  { symbol: "XLF",   name: "Financial Select SPDR",     exchange: "NYSE",   sector: "ETF" },
  { symbol: "XLK",   name: "Technology Select SPDR",    exchange: "NYSE",   sector: "ETF" },
  { symbol: "ARKK",  name: "ARK Innovation ETF",        exchange: "NYSE",   sector: "ETF" },
  { symbol: "SOXL",  name: "Direxion Semi Bull 3X",     exchange: "NYSE",   sector: "ETF" },
];
